# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Arsham Vashisth
description: "A data enthusiast with a strong interest in Machine Learning and analytics. I enjoy using data to solve real world problems and support better decision making. This portfolio showcases a selection of my projects, each focused on creating practical and meaningful impact. Feel free to explore my work, visit my GitHub and LinkedIn, or download my resume below."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Melbourne, AU"
resume_url: /docs/resume.docx
avatar_image: /img/pfolio img.png

#-------------------------------
# Contact links
linkedln: "https://linkedln.com/#" # Add your linkedln handle
github: "https://github.com/#"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/





